const allArmors = []; 

function defineAllArmors() {
    allArmors[0] = {
        isDefaultItem: true,
        itemType: `armor`,
        itemEquipType: [`head`],
        index: 0,
        icon: `url("./images/head.png")`,
        name: `Head`,
        // type: `melee`,
        resists: [0,0,0,0,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: null,
        disrupt: null,
        block: null,
    }
    allArmors[1] = {
        isDefaultItem: true,
        itemType: `armor`,
        itemEquipType: [`torso`],
        index: 1,
        icon: `url("./images/torso.png")`,
        name: `Torso`,
        // type: `melee`,
        resists: [0,0,0,0,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: null,
        disrupt: null,
        block: null,
    }
    allArmors[2] = {
        isDefaultItem: true,
        itemType: `armor`,
        itemEquipType: [`arms`],
        index: 2,
        icon: `url("./images/arms.png")`,
        name: `Arms`,
        // type: `melee`,
        resists: [0,0,0,0,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: null,
        disrupt: null,
        block: null,
    }
    allArmors[3] = {
        isDefaultItem: true,
        itemType: `armor`,
        itemEquipType: [`legs`],
        index: 3,
        icon: `url("./images/legs.png")`,
        name: `Legs`,
        // type: `melee`,
        resists: [0,0,0,0,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: null,
        disrupt: null,
        block: null,
    }
    allArmors[4] = {
        isDefaultItem: true,
        itemType: `armor`,
        itemEquipType: [`amulet1`],
        index: 4,
        icon: `url("./images/amulet.png")`,
        name: `Amulet 1`,
        // type: `melee`,
        resists: [0,0,0,0,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: null,
        disrupt: null,
        block: null,
    }
    allArmors[5] = {
        isDefaultItem: true,
        itemType: `armor`,
        itemEquipType: [`amulet2`],
        index: 5,
        icon: `url("./images/amulet.png")`,
        name: `Amulet 2`,
        // type: `melee`,
        resists: [0,0,0,0,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: null,
        disrupt: null,
        block: null,
    }
    allArmors[6] = {
        isDefaultItem: true,
        itemType: `armor`,
        itemEquipType: [`quickAccess1`],
        index: 6,
        icon: `url("./images/quickAccess.png")`,
        name: `Quick Access 1`,
        // type: `melee`,
        resists: [0,0,0,0,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: null,
        disrupt: null,
        block: null,
    }
    allArmors[7] = {
        isDefaultItem: true,
        itemType: `armor`,
        itemEquipType: [`quickAccess2`],
        index: 7,
        icon: `url("./images/quickAccess.png")`,
        name: `Quick Access 2`,
        // type: `melee`,
        resists: [0,0,0,0,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: null,
        disrupt: null,
        block: null,
    }
    allArmors[8] = {
        isDefaultItem: false,
        itemType: `armor`,
        itemEquipType: [`torso`],
        index: 8,
        icon: `url("./images/oldShirt.png")`,
        name: `Old Shirt`,
        // type: `melee`,
        resists: [1,0,0,0,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: null,
        disrupt: null,
        block: null,
    }
    allArmors[9] = {
        isDefaultItem: false,
        itemType: `armor`,
        itemEquipType: [`legs`],
        index: 9,
        icon: `url("./images/trustyBelt.png")`,
        name: `Trusty Belt`,
        // type: `melee`,
        resists: [0,0,1,1,0,0,0,0,0],
        damage: null,
        range: null,
        parry: null,
        dodge: 2,
        disrupt: null,
        block: null,
    }
}

defineAllArmors();

export { allArmors } ;